UPSTREAM:net: mii: report 0 for unknown lp_advertising
The newly introduced mii_ethtool_get_link_ksettings function sets
lp_advertising to an uninitialized value when BMCR_ANENABLE is not
set:

drivers/net/mii.c: In function 'mii_ethtool_get_link_ksettings':
drivers/net/mii.c:224:2: error: 'lp_advertising' may be used uninitialized in this function [-Werror=maybe-uninitialized]

As documented in include/uapi/linux/ethtool.h, the value is
expected to be zero when we don't know it, so let's initialize
it to that.

Fixes: bc8ee596afe8 ("net: mii: add generic function to support ksetting support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit dc0b2c9cb47a2176e1f341bfdc770745d24e072c)

BUG=b:149304110
TEST=reboot,suspend/resume, and netperf tests on teemo (fizz)

Signed-off-by: Grant Grundler <grundler@chromium.org>
Change-Id: I0e791675f59b921524036b9883f32b99f7bafd74
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2203614
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Sean Paul <seanpaul@chromium.org>