CHROMIUM: Revert "mac80211: Do not send Layer 2 Update frame before authorization"
This reverts commit 622c77a3addefa54d61205177635409de87a8a7c.

Pree-merge revert is necessary due to conflict with out-of-tree
iwl7000 code in Chrome OS kernel repository.

drivers/net/wireless/iwl7000/hdrs/mac80211-bp.h:2208:6: error:
	static declaration of 'cfg80211_send_layer2_update' follows non-static declaration

BUG=chromium:1044981
TEST=build after merge

Change-Id: I73265dcd895f8d7f535543fa695b21c7073237e1
Signed-off-by: Guenter Roeck <groeck@chromium.org>