CHROMIUM: Revert "cfg80211/mac80211: make ieee80211_send_layer2_update a public function"
This reverts commit 9d9805179c7c195a9468a31d93974d1cf1800ae9.

Pre-merge revert is necessary due to conflict with out-of-tree
iwl7000 code in Chrome OS kernel repository.

drivers/net/wireless/iwl7000/hdrs/mac80211-bp.h:2208:6: error:
	static declaration of 'cfg80211_send_layer2_update' follows non-static declaration

BUG=chromium:1044981
TEST=build after merge

Change-Id: Ice9a8aec44e4dc31caa374db02c064cfe54e7b97
Signed-off-by: Guenter Roeck <groeck@chromium.org>