FIXUP: BACKPORT: FROMGIT: media: cec: i2c: ch7322: Add ch7322 CEC controller driver
The driver depends on CEC_NOTIFIER. If it is not set, we get:

drivers/media/cec/i2c/ch7322.c: In function 'ch7322_probe':
drivers/media/cec/i2c/ch7322.c:513:14: error: 'struct cec_adapter' has no member named 'notifier'

as reported by 0-day.

BUG=b:146576073
TEST=cec-ctl on endeavour

Change-Id: I7d9cf332d5317a7162c701625b48850868cc138e
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2286054
Reviewed-by: Jeff Chase <jnchase@google.com>