FIXUP: FROMLIST: usb: mausb_host: MA-USB PAL events processing
0-day reports:

drivers/usb/host/mausb/utils.c: In function 'mausb_host_dev_read':
drivers/usb/host/mausb/utils.c:92:7: error:
	implicit declaration of function 'copy_to_user';

copy_to_user() is declared in uaccess.h, which therefore needs
to be included.

BUG=b:148855950
TEST=Build arc:allmodconfig

Change-Id: I7a5c47a76cfeec9f9e22853328e4e76e34825159
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2315935
Reviewed-by: Joe Tessler <jrt@chromium.org>